import io
import os
import html
from datetime import datetime
from typing import List, Dict, Any, Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

BANNER_CACHE = None

def get_pdf_banner() -> str:
    global BANNER_CACHE
    return BANNER_CACHE or ""


def safe_html(val: Any, fallback: str = "N/A") -> str:
    if val is None or val == "":
        return fallback
    s = str(val)
    return html.escape(s)


def format_date_str(date_str: Optional[str]) -> str:
    if not date_str:
        return "N/A"
    try:
        dt = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
        return dt.strftime("%d %b %Y %H:%M")
    except Exception:
        return date_str


class ReportCanvas(canvas.Canvas):
    """
    Two-pass canvas for page numbering, header rule, and footer.
    """
    _pageNumber: int

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states: List[Dict[str, Any]] = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        start_page_fn = getattr(self, "_startPage", None)
        if callable(start_page_fn):
            start_page_fn()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_decorations(self, page_count: int):
        page_num = getattr(self, "_pageNumber", 1)
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Top Header line on pages 2+
        if page_num > 1:
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(36, 806, 559, 806)
            self.drawString(36, 812, "EI HUB ENTERPRISE SYSTEM — OFFICIAL REPORT")
            self.drawRightString(559, 812, f"Page {page_num} of {page_count}")

        # Bottom Footer line on all pages
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(36, 45, 559, 45)

        now_str = datetime.now().strftime("%d %b %Y %H:%M:%S")
        self.drawString(36, 30, f"Confidential — Generated by EI HUB System on {now_str}")
        self.drawRightString(559, 30, f"Page {page_num} of {page_count}")

        self.restoreState()


def normalize_report_type(raw_type: str) -> tuple:
    """
    Returns (canonical_key, display_title)
    """
    if not raw_type:
        return "inventory", "INVENTORY REPORT"
    cleaned = raw_type.strip().lower().replace("_", " ").replace("-", " ")
    
    if "low stock" in cleaned:
        return "low_stock", raw_type.strip().upper()
    elif "monthly" in cleaned:
        return "monthly", raw_type.strip().upper()
    elif any(k in cleaned for k in ["transaction", "total register", "sale register", "transfer register", "return register", "adjustment register"]):
        return "transaction", raw_type.strip().upper()
    else:
        return "inventory", raw_type.strip().upper()


def generate_report_pdf_bytes_internal(
    report_type: str,
    components: List[Dict[str, Any]],
    requests: List[Dict[str, Any]],
    stats: Dict[str, Any],
    date_range: str,
    generated_by: str,
    from_date: Optional[str] = None,
    to_date: Optional[str] = None
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=36,
        rightMargin=36,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=16,
        leading=20,
        textColor=colors.HexColor('#0F172A'),
        spaceAfter=4
    )
    meta_style = ParagraphStyle(
        'DocMeta',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor('#475569'),
        spaceAfter=10
    )
    section_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#1E293B'),
        spaceBefore=12,
        spaceAfter=6
    )
    cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#1E293B')
    )
    cell_bold_style = ParagraphStyle(
        'TableCellBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#0F172A')
    )
    header_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=colors.white
    )

    canonical_key, display_title = normalize_report_type(report_type)

    elements = []

    # Title & Meta Header
    elements.append(Paragraph(safe_html(display_title), title_style))
    meta_text = f"EI HUB Innoventry System | School of Innovation | Generated by: {safe_html(generated_by)} | Date Range: {safe_html(date_range)}"
    elements.append(Paragraph(meta_text, meta_style))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#7C3AED'), spaceAfter=10))

    # Calculate Stats
    total_categories = len(set(c.get("category", "Uncategorized") for c in components)) if components else 0
    total_components = len(components)
    avail_stock = sum(c.get("available_stock", 0) for c in components)
    borr_stock = sum(c.get("borrowed_stock", 0) for c in components)
    low_stock_cnt = sum(1 for c in components if (c.get("available_stock", 0) <= 5))
    
    total_reqs = len(requests)

    # KPI Summary Cards Table
    kpi_items = [
        ("CATEGORIES", str(total_categories), "#0F172A"),
        ("COMPONENTS", str(total_components), "#0F172A"),
        ("AVAILABLE", str(avail_stock), "#10B981"),
        ("BORROWED", str(borr_stock), "#F97316"),
        ("LOW STOCK", str(low_stock_cnt), "#EF4444"),
        ("TRANSACTIONS", str(total_reqs), "#3B82F6"),
    ]

    kpi_cells = []
    for label, val, hex_c in kpi_items:
        cell_p = Paragraph(f"<b><font size=7 color='#64748B'>{label}</font></b><br/><font size=11 color='{hex_c}'><b>{val}</b></font>", cell_style)
        kpi_cells.append(cell_p)

    kpi_table = Table([kpi_cells], colWidths=[86.5]*6)
    kpi_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 10))

    if canonical_key in ["inventory", "low_stock"]:
        # Component inventory table
        sec_title = "Laboratory Inventory Stock Breakdown" if canonical_key == "inventory" else "Low Stock Items Requiring Action"
        elements.append(Paragraph(sec_title, section_style))

        headers = ["SKU", "Component Name", "Category", "Total", "Avail", "Borr", "Location"]

        target_components = components
        if canonical_key == "low_stock":
            target_components = [c for c in components if (c.get("available_stock", 0) <= 5)]

        if not target_components:
            no_data_cell = Paragraph("No inventory items found matching report criteria.", cell_style)
            t = Table([[Paragraph(h, header_style) for h in headers], [no_data_cell, "", "", "", "", "", ""]], colWidths=[65, 140, 110, 45, 45, 45, 73])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#7C3AED')),
                ('SPAN', (0, 1), (6, 1)),
                ('ALIGN', (0, 1), (6, 1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ]))
            elements.append(t)
        else:
            table_rows = [[Paragraph(h, header_style) for h in headers]]
            for c in target_components:
                sku = safe_html(c.get("sku") or f"COMP-{str(c.get('id', ''))[:4].upper()}")
                name = safe_html(c.get("name"))
                cat = safe_html(c.get("category"))
                tot = safe_html(c.get("total_stock", 0))
                av = safe_html(c.get("available_stock", 0))
                bo = safe_html(c.get("borrowed_stock", 0))
                loc = safe_html(c.get("location") or f"{c.get('cabinet', 'Lab A')}, {c.get('shelf', 'Shelf 1')}")

                table_rows.append([
                    Paragraph(sku, cell_bold_style),
                    Paragraph(name, cell_style),
                    Paragraph(cat, cell_style),
                    Paragraph(tot, cell_style),
                    Paragraph(av, cell_style),
                    Paragraph(bo, cell_style),
                    Paragraph(loc, cell_style),
                ])

            t = Table(table_rows, colWidths=[65, 140, 110, 45, 45, 45, 73])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#7C3AED')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(t)

    # Transaction Log / Request History Table
    if canonical_key in ["transaction", "monthly", "inventory"]:
        if canonical_key == "inventory":
            elements.append(Spacer(1, 10))

        sec_title = "Borrow & Return Transaction Log" if canonical_key != "monthly" else "Monthly Activity Log"
        elements.append(Paragraph(sec_title, section_style))

        headers = ["Tx Code", "Date & Time", "Student Name", "Roll No", "Component", "Qty", "Status"]

        if not requests:
            no_data_cell = Paragraph("No transaction requests recorded for this period.", cell_style)
            t = Table([[Paragraph(h, header_style) for h in headers], [no_data_cell, "", "", "", "", "", ""]], colWidths=[65, 90, 110, 65, 110, 35, 48])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563EB')),
                ('SPAN', (0, 1), (6, 1)),
                ('ALIGN', (0, 1), (6, 1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ]))
            elements.append(t)
        else:
            table_rows = [[Paragraph(h, header_style) for h in headers]]
            for r in requests:
                code = safe_html(r.get("request_code") or f"REQ-{str(r.get('id', ''))[:8].upper()}")
                dt = safe_html(format_date_str(r.get("requested_at")))
                sname = safe_html(r.get("student_name"))
                sroll = safe_html(r.get("student_register_no") or r.get("student_roll_no"))
                comp = safe_html(r.get("component_name"))
                qty = safe_html(r.get("quantity", 1))
                st = safe_html(str(r.get("status", "")).upper())

                table_rows.append([
                    Paragraph(code, cell_bold_style),
                    Paragraph(dt, cell_style),
                    Paragraph(sname, cell_style),
                    Paragraph(sroll, cell_style),
                    Paragraph(comp, cell_style),
                    Paragraph(qty, cell_style),
                    Paragraph(st, cell_style),
                ])

            t = Table(table_rows, colWidths=[65, 90, 110, 65, 110, 35, 48])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2563EB')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(t)

    doc.build(elements, canvasmaker=ReportCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


def generate_inventory_report_pdf(
    components: List[Dict[str, Any]], 
    requests: List[Dict[str, Any]], 
    stats: Dict[str, Any], 
    date_range: str, 
    generated_by: str,
    from_date: Optional[str] = None,
    to_date: Optional[str] = None
) -> bytes:
    return generate_report_pdf_bytes_internal("Inventory Report", components, requests, stats, date_range, generated_by, from_date, to_date)


def generate_low_stock_report_pdf(
    components: List[Dict[str, Any]], 
    requests: List[Dict[str, Any]], 
    stats: Dict[str, Any], 
    date_range: str, 
    generated_by: str,
    from_date: Optional[str] = None,
    to_date: Optional[str] = None
) -> bytes:
    return generate_report_pdf_bytes_internal("Low Stock Alert", components, requests, stats, date_range, generated_by, from_date, to_date)


def generate_monthly_report_pdf(
    components: List[Dict[str, Any]], 
    requests: List[Dict[str, Any]], 
    stats: Dict[str, Any], 
    date_range: str, 
    generated_by: str,
    from_date: Optional[str] = None,
    to_date: Optional[str] = None
) -> bytes:
    return generate_report_pdf_bytes_internal("Monthly Summary", components, requests, stats, date_range, generated_by, from_date, to_date)


def generate_transaction_report_pdf(
    components: List[Dict[str, Any]], 
    requests: List[Dict[str, Any]], 
    stats: Dict[str, Any], 
    date_range: str, 
    generated_by: str,
    from_date: Optional[str] = None,
    to_date: Optional[str] = None
) -> bytes:
    return generate_report_pdf_bytes_internal("Transaction Log", components, requests, stats, date_range, generated_by, from_date, to_date)
