import re
import os

def apply_backend_changes():
    with open('backend/app.py', 'r', encoding='utf-8') as f:
        content = f.read()

    new_endpoints = """

# ==========================================
# REPORT PDF GENERATION & EMAIL
# ==========================================
from pydantic import BaseModel
from typing import List, Optional
import base64

class EmailReportRequest(BaseModel):
    report_type: str
    to: List[str]
    cc: Optional[List[str]] = []
    bcc: Optional[List[str]] = []
    subject: str
    message: str

async def send_brevo_email_advanced(to_emails: List[str], subject: str, html_content: str, cc_emails: List[str] = None, bcc_emails: List[str] = None, attachment: Optional[list] = None) -> bool:
    api_key = os.environ.get("BREVO_API_KEY") or os.environ.get("VITE_BREVO_API_KEY")
    sender_email = os.environ.get("BREVO_SENDER_EMAIL") or os.environ.get("VITE_BREVO_SENDER_EMAIL", "eihubsoi@gmail.com")
    sender_name = os.environ.get("BREVO_SENDER_NAME") or os.environ.get("VITE_BREVO_SENDER_NAME", "EI HUB Support")
    
    to_list = [{"email": email.strip()} for email in to_emails if email.strip()]
    if not to_list:
        return False

    if not api_key:
        print(f"[Brevo Fallback Dev Mode] To: {to_list} | Subject: {subject}")
        return True
        
    payload = {
        "sender": {"name": sender_name, "email": sender_email},
        "to": to_list,
        "subject": subject,
        "htmlContent": html_content
    }
    
    if cc_emails:
        cc_list = [{"email": email.strip()} for email in cc_emails if email.strip()]
        if cc_list: payload["cc"] = cc_list
        
    if bcc_emails:
        bcc_list = [{"email": email.strip()} for email in bcc_emails if email.strip()]
        if bcc_list: payload["bcc"] = bcc_list
    
    if attachment:
        payload["attachment"] = attachment
        
    headers = {
        "accept": "application/json",
        "content-type": "application/json",
        "api-key": api_key
    }
    
    try:
        async with httpx.AsyncClient(timeout=15.0) as http_client:
            response = await http_client.post("https://api.brevo.com/v3/smtp/email", json=payload, headers=headers)
            if response.status_code in [200, 201, 202]:
                print(f"Brevo email successfully sent to {to_list}")
                return True
            else:
                print(f"Brevo email failed ({response.status_code}): {response.text}")
                return False
    except Exception as e:
        print(f"Error calling Brevo: {e}")
        return False

async def generate_report_pdf_bytes(report_type: str, user: dict) -> bytes:
    try:
        from fpdf import FPDF
    except ImportError:
        raise Exception("fpdf2 is not installed")
        
    # Fetch Data
    components = await db_query("SELECT * FROM components") or []
    requests = await db_query("SELECT * FROM requests") or []
    
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.add_page()
    
    # Header
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(15, 30, 60)
    pdf.cell(0, 10, "EI HUB Enterprise - Official Report", new_x="LMARGIN", new_y="NEXT", align="C")
    
    pdf.set_font("helvetica", "I", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "School of Innovation", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(10)
    
    # Metadata
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, f"Report Type: {report_type}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 6, f"Generated By: {user.get('name', 'Admin')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    
    # Summary Table
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "System Overview", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 10)
    total_comps = len(components)
    total_stock = sum(c.get('total_stock', 0) for c in components)
    
    pdf.cell(50, 8, "Total Categories:", border=1)
    pdf.cell(50, 8, str(len(set(c.get('category', '') for c in components))), border=1, new_x="LMARGIN", new_y="NEXT")
    
    pdf.cell(50, 8, "Total Components:", border=1)
    pdf.cell(50, 8, str(total_comps), border=1, new_x="LMARGIN", new_y="NEXT")
    
    pdf.cell(50, 8, "Total Stock Units:", border=1)
    pdf.cell(50, 8, str(total_stock), border=1, new_x="LMARGIN", new_y="NEXT")
    
    pdf.ln(10)
    
    # Example table of some components (limit 20)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 10, "Component Snapshot (Top 20)", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "B", 9)
    pdf.cell(70, 7, "Name", border=1)
    pdf.cell(40, 7, "Category", border=1)
    pdf.cell(30, 7, "Total Stock", border=1)
    pdf.cell(30, 7, "Available", border=1, new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 8)
    for c in components[:20]:
        pdf.cell(70, 6, str(c.get('name', ''))[:35], border=1)
        pdf.cell(40, 6, str(c.get('category', ''))[:20], border=1)
        pdf.cell(30, 6, str(c.get('total_stock', 0)), border=1)
        pdf.cell(30, 6, str(c.get('available_stock', 0)), border=1, new_x="LMARGIN", new_y="NEXT")
        
    return pdf.output()

@app.get("/api/admin/reports/preview-pdf")
async def preview_report_pdf(reportType: str = "Inventory Report", user: dict = Depends(get_current_user)):
    if user.get("role") not in ["admin", "super_admin", "faculty"]:
        raise HTTPException(status_code=403, detail="Forbidden")
        
    try:
        pdf_bytes = await generate_report_pdf_bytes(reportType, user)
        response = Response(content=pdf_bytes, media_type="application/pdf")
        response.headers["Content-Disposition"] = f"inline; filename=preview.pdf"
        return response
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/admin/reports/email-pdf")
async def email_report_pdf(req: EmailReportRequest, user: dict = Depends(get_current_user)):
    if user.get("role") not in ["admin", "super_admin", "faculty"]:
        raise HTTPException(status_code=403, detail="Forbidden")
        
    try:
        pdf_bytes = await generate_report_pdf_bytes(req.report_type, user)
        b64_pdf = base64.b64encode(pdf_bytes).decode('utf-8')
        
        filename = f"{req.report_type.replace(' ', '_')}_{datetime.now().strftime('%Y-%m-%d')}.pdf"
        
        attachment = [{
            "name": filename,
            "content": b64_pdf
        }]
        
        html = req.message.replace("\\n", "<br>")
        
        success = await send_brevo_email_advanced(
            to_emails=req.to,
            subject=req.subject,
            html_content=html,
            cc_emails=req.cc,
            bcc_emails=req.bcc,
            attachment=attachment
        )
        
        if success:
            await log_activity(user["uid"], user["name"], "EMAIL_REPORT", "REPORTS", req.report_type, {"recipients": req.to}, "info")
            return {"status": "success", "message": "Email sent"}
        else:
            raise HTTPException(status_code=500, detail="Failed to send email via Brevo")
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

"""

    content += new_endpoints

    with open('backend/app.py', 'w', encoding='utf-8') as f:
        f.write(content)

apply_backend_changes()
